# Generated by Django 3.1.2 on 2021-05-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='Amazon',
        ),
    ]
