# Generated by Django 3.1.2 on 2021-05-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_netflix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotstar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subscribers', models.IntegerField()),
                ('premium', models.IntegerField()),
                ('content', models.CharField(max_length=100)),
            ],
        ),
    ]
