# Generated by Django 3.1.2 on 2021-05-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_hotstar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subscribers', models.IntegerField()),
                ('premium', models.IntegerField()),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mxplayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subscribers', models.IntegerField()),
                ('premium', models.IntegerField()),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zee5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subscribers', models.IntegerField()),
                ('premium', models.IntegerField()),
                ('content', models.CharField(max_length=100)),
            ],
        ),
    ]
